FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY workers/email_worker/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy common + full workers directory
COPY common /app/common
COPY workers /app/workers

RUN touch /app/workers/__init__.py \
    && touch /app/workers/email_worker/__init__.py

ENV PYTHONPATH=/app

CMD ["python", "-m", "workers.email_worker.email_worker"]
